import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",// overrides the default and template if you don't want it to apply in a certain page
    default: "Developers Network", //This is the default if no title metadata is defined
    template: "%s | Developers Network", // Every route will have this as their title if they have the title metadata specified e.g Blogs route if it has blog title metadata it will be "blogs | Developers Network"
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            background: "lightblue",
            padding: "1rem",
          }}
        >
          Header
        </header>

        {children}

        <footer
          style={{
            background: "aqua",
            padding: "1rem",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
